# Generated by Django 4.2.7 on 2024-04-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['created_on'], 'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
    ]
